name: Publish changes

on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install packages
        run: npm i

      - name: Build script
        run: node run build

      - name: Publish to pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: build
          target-branch: pages
